---
- name: Ensure sudoers file exist
  stat: path='/etc/sudoers'
  register: sudoers

- name: Fix sudoers password asking
  when: sudoers.stat.exists == true and ansible_distribution == 'Ubuntu'
  lineinfile:
    dest: /etc/sudoers
    line: "{{ ansible_env.SUDO_USER }} ALL=(ALL) NOPASSWD:ALL"
